apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-group-binding
subjects:
  - kind: Group
    name: admin-group
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: cluster-updater-role
  apiGroup: rbac.authorization.k8s.io