apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view-group-binding
subjects:
  - kind: Group
    name: view-group
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: resources-reader-role
  apiGroup: rbac.authorization.k8s.io